base_url = "https://micahkepe.com/blog"
title = "Micah's Secret Blog"
author = "Micah Kepe"
theme = "radion"
description = "An assortment of my ramblings and random adventures."
generate_feeds = true

taxonomies = [
    # You can enable/disable RSS
    {name = "categories", feed = true},
    {name = "tags", feed = true},
 ]

compile_sass = true
default_language = "en"
build_search_index = true
generate_sitemap = true
generate_robots_txt = true
minify_html = true

[markdown]
bottom_footnotes = true
external_links_target_blank = true
external_links_external = true
external_links_no_referrer = true
lazy_async_image = true
github_alerts = true
insert_anchor_links = "heading"

[markdown.highlighting]
style = "class"
dark_theme = "one-dark-pro"
light_theme = "everforest-light"
error_on_missing_language = true

[search]
index_format = "elasticlunr_json"
include_title = true
include_description = true
include_content = true

[extra]
radion_title = "Micah's Secret Blog"
github = "https://github.com/micahkepe"
radion_menu = [
    {url = "$BASE_URL/", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "https://micahkepe.com/", name = "Main Site"},
]

codeblock = true
latex = true
enable_search = true
theme = "toggle" # options: {light, dark, auto, toggle}

# Comment sections
comments = true
giscus_repo = "micahkepe/blog"
giscus_repo_id = "R_kgDONfHznQ"
giscus_data_category_id = "DIC_kwDONfHznc4CnQJ4"

# Post revision histories
revision_history = true
blog_github_repo_url = "https://github.com/micahkepe/blog"
